//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerChatApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomRoster
    {
        public int Roster_Id { get; set; }
        public int Chat_Id { get; set; }
        public string UserName { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual User User { get; set; }
    }
}
